name = "espro"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "espro"
database_id = "ced36175-205d-4871-a3a5-6ece9932401f"   # saída de: wrangler d1 create espro

# Sem segredos obrigatórios: a chave dos logins é criada sozinha no D1.
# Opcional (variável, não segredo): ADMIN_EMAIL -> troca o e-mail do administrador (padrão: vitortozeti@gmail.com)
